### ISSUE TITLE
TST: unit tests fail after MPL 1.4 update

### ISSUE THREAD

**Issue by bryevdv** [mpld3/mplexporter#29]
```
bryan@laptop (git:master) ~/work/bokeh/bokeh/mplexporter $ conda list matplotlib
# packages in environment at /Users/bryan/anaconda:
#
matplotlib                1.4.0                np18py27_0
```

```
bryan@laptop (git:master) ~/work/bokeh/bokeh/mplexporter $ nosetests 
..E.....F..
======================================================================
ERROR: bokeh.mplexporter.tests.test_basic.test_path_collection
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/bryan/anaconda/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/bryan/work/bokeh/bokeh/mplexporter/tests/test_basic.py", line 75, in test_path_collection
    _assert_output_equal(fake_renderer_output(fig, FakeRenderer),
  File "/Users/bryan/work/bokeh/bokeh/mplexporter/tests/test_basic.py", line 15, in fake_renderer_output
    exporter.run(fig)
  File "/Users/bryan/work/bokeh/bokeh/mplexporter/exporter.py", line 49, in run
    self.crawl_fig(fig)
  File "/Users/bryan/work/bokeh/bokeh/mplexporter/exporter.py", line 116, in crawl_fig
    self.crawl_ax(ax)
  File "/Users/bryan/work/bokeh/bokeh/mplexporter/exporter.py", line 138, in crawl_ax
    self.draw_collection(ax, collection)
  File "/Users/bryan/work/bokeh/bokeh/mplexporter/exporter.py", line 267, in draw_collection
    mplobj=collection)
  File "/Users/bryan/work/bokeh/bokeh/mplexporter/renderers/base.py", line 255, in draw_path_collection
    offsets, styles):
  File "/Users/bryan/work/bokeh/bokeh/mplexporter/renderers/base.py", line 192, in _iter_path_collection
    if not path_transforms:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

======================================================================
FAIL: bokeh.mplexporter.tests.test_basic.test_legend_dots
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/bryan/anaconda/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/bryan/work/bokeh/bokeh/mplexporter/tests/test_basic.py", line 201, in test_legend_dots
    """)
  File "/Users/bryan/work/bokeh/bokeh/mplexporter/tests/test_basic.py", line 21, in _assert_output_equal
    assert line1 == line2
AssertionError

----------------------------------------------------------------------
Ran 11 tests in 1.233s

FAILED (errors=1, failures=1)
```

**Comment by danielballan** [comment]
Three tests are failing on mpl 1.5.0rc1:

1. test_path_collection -- resolved, PR forthcoming
2. test_image -- new size of rendered image is 1220, was formerly 1240
3. test_legend_dots -- path has 4 vertices; 5 are expected, see below

Actual:
opening figure
opening axes
draw line with 3 points
draw 3 markers
opening legend
draw text 'None' None
draw line with 2 points
draw text 'label' None
draw 2 markers
draw text 'dots' None
draw path with **4** vertices
closing legend
losing axes
closing figure

Expected:
opening figure
opening axes
draw line with 3 points
draw 3 markers
opening legend
draw line with 2 points
draw text 'label' None
draw 2 markers
draw text 'dots' None
draw path with **5** vertices
closing legend
closing axes
closing figure

**Comment by tacaswell** [comment]
mpl fixed a bug where we were not emitting close-path codes on some paths
and instead were just moving back to where the path started which gets the
join at the start/end point wrong.

**Comment by danielballan** [comment]
@jakevdp That leaves one test left that we don't understand: the slight change in the image size. I suggest we release mpld3 and let this be a known issue. I think our goal is to keep mpld3 alive/relevant on a modern stack until matplotlib traitlets is ready, at which time most or all of this code will be moot.

**Comment by danielballan** [comment]
bump

**Comment by jakevdp** [comment]
Sounds good
